blank_issues_enabled: true
contact_links:
    - name: General help request
      url: https://wordpress.org/support/plugin/two-factor/
      about: For general help requests, create a new topic in the Two-Factor support forum on WordPress.org.