name: Test

on: [push, pull_request]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    lint-js-css:
        name: Lint JS & CSS
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

            - name: Setup Node
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                cache: 'npm'
                node-version-file: '.nvmrc'

            - name: Install NPM dependencies
              run: npm install

            - name: Lint JS
              run: npm run lint:js

            - name: Lint CSS
              run: npm run lint:css

    lint-php-and-compatibility:
        name: Lint PHP & PHP Compatibility checks.
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

            - name: Setup PHP and Composer
              uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
              with:
                php-version: '8.3'

            - name: Setup Node
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                cache: 'npm'
                node-version-file: '.nvmrc'

            - name: Install NPM dependencies
              run: npm install

            - name: Lint PHP
              run: npm run lint:php || true # Ignore for now.

            - name: Lint PHP Compatibility
              run: composer lint-compat

            - name: PHPStan
              run: npm run lint:phpstan

    test-php:
        name: Test PHP ${{ matrix.php }} ${{ matrix.wp != '' && format( ' (WP {0}) ', matrix.wp ) || '' }}
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                php:
                  - '8.5'
                  - '8.4'
                  - '8.3'
                  - '8.2'
                  - '8.1'
                  - '8.0'
                  - '7.4'
                  - '7.3'
                  - '7.2'
                wp:
                  - latest
                  - trunk
                  - '6.9'
                exclude:
                  - php: '7.3'
                    wp: trunk
                  - php: '7.2'
                    wp: trunk
                  - php: '7.3'
                    wp: latest
                  - php: '7.2'
                    wp: latest

        env:
            WP_ENV_PHP_VERSION: ${{ matrix.php }}
            WP_ENV_CORE: ${{ matrix.wp == 'trunk' && 'WordPress/WordPress' || format( 'https://wordpress.org/wordpress-{0}.zip', matrix.wp ) }}

        steps:
            - name: Checkout
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

            - name: Setup PHP
              uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
              with:
                php-version: '8.3'

            - name: Setup Node
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                cache: 'npm'
                node-version-file: '.nvmrc'

            - name: Install NPM dependencies
              run: npm install

            - name: Start the Docker testing environment
              uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: npm run env start -- --xdebug=coverage

            - name: Composer install
              run: |
                rm composer.lock || true # We need to install fresh.
                npm run composer install

            - name: Versions
              run: |
                npm run env run cli php -- -v
                npm run env run cli wp core version

            - name: Test
              run: npm run test

            - name: Upload code coverage report
              if: ${{ matrix.php == '8.3' && matrix.wp == 'latest' }}
              uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
              with:
                file: tests/logs/clover.xml
                flags: phpunit
                fail_ci_if_error: false

    build:
        name: Build
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

            - name: Setup PHP
              uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
              with:
                php-version: '8.3'

            - name: Setup Node
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
              with:
                cache: 'npm'
                node-version-file: '.nvmrc'

            - name: Install NPM dependencies
              run: npm install

            - name: Build
              run: npm run build
